# Generated by Django 4.2.10 on 2024-02-29 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResultYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hruba_mzda', models.FloatField()),
                ('superhruba_mzda', models.FloatField()),
                ('zdravotni_pojisteni', models.FloatField()),
                ('socialni_pojisteni', models.FloatField()),
                ('dan_pred_slevami', models.FloatField()),
                ('dan_po_slevach', models.FloatField()),
                ('cista_mzda', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
