# Generated by Django 4.2.10 on 2024-03-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_calculationresultyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='pouzite_slevy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='calculationresultyear',
            name='pouzite_slevy',
            field=models.TextField(blank=True, default=''),
        ),
    ]
